### ISSUE TITLE
Algo interesante

### ISSUE THREAD

**Issue by Mariovega99** [terantemental/borrame#10]
ixu

**Comment by RSanchez98** [comment]
ishush

**Comment by RSanchez98** [comment]
![wheezy](https://user-images.githubusercontent.com/45387295/49207284-c9cb3200-f3b4-11e8-89e1-238d18e49e83.jpg)

**Comment by Mariovega99** [comment]
![pug cachorro](https://user-images.githubusercontent.com/45387344/49207345-f41cef80-f3b4-11e8-8a6d-d208053e9bd5.jpg)

**Comment by Mariovega99** [comment]
![paco](https://user-images.githubusercontent.com/45387344/49207382-0f87fa80-f3b5-11e8-93c5-bf4223844782.png)

**Comment by piltrafillaeme** [comment]
![aitana](https://user-images.githubusercontent.com/45387274/49207383-10b92780-f3b5-11e8-9ba9-df62e51466ad.jpg)

**Comment by RSanchez98** [comment]
![1539198110_433123_1539208767_noticia_normal](https://user-images.githubusercontent.com/45387295/49207419-2a5a6f00-f3b5-11e8-83cc-469a981fa183.jpg)
